### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Haxk20** [SpadesX/SpadesX#4]
- [x] - Movement in server
- [x] - Fall damage
- [x] - Grenades
- [x] - Grenades player damage
- [x] - Fix the damn ID bug
- [x] - Implement actual gameplay (intel pickup etc.)
- [x] - Add ban command
- [x] - Normalize vectors to prevent speed movement hacks.
- [x] - Floating block detection.
- [x] - Map split sending
- [x] - Fix invisible players on joining
- [x] - Make players not die on new user joining (libvxl_write takes way too long to fixing causing physics to go out of sync too much making players get fall damage).
- [x] - Grenade floating block destroying

More to be added later.

**Comment by sodomon2** [comment]
Support for game modes?

**Comment by Haxk20** [comment]
> Support for game modes?

That will be added later. Im mainly focusing on things torwards having an functional server and ofc the things for basic gameplay. But yes i have game modes on a list to add once basic things are done.

**Comment by Fran6nd** [comment]
Hello guys! Wonderful job here :) do you plan adding a scripting interface so we can mod the server without recompiling? I successfully did some dirty experiments with Lua locally... I do love Lua: written in C, easy and fast to bind/sandbox...

Or you want it fully compiled?

BTW great job :)

**Comment by Haxk20** [comment]
> Hello guys! Wonderful job here :) do you plan adding a scripting interface so we can mod the server without recompiling? I successfully did some dirty experiments with Lua locally... I do love Lua: written in C, easy and fast to bind/sandbox...
> 
> Or you want it fully compiled?
> 
> BTW great job :)

Yes an scripting interface is planned later down the line. We are just mostly focusing on WIP features right now.
